# -*- coding: utf-8 -*-
"""AnalisePCG - PIBxViolencia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1HM2TFujpIDOCq1wO1GSS0hzrK4nEpB
"""

import pandas as pd

dados_tratados_2015 = "dados/dados_tratados_2015.csv"
dados_tratados_2016 = "dados/dados_tratados_2016.csv"
dados_tratados_2017 = "dados/dados_tratados_2017.csv"
dados_tratados_2018 = "dados/dados_tratados_2018.csv"
dados_tratados_2019 = "dados/dados_tratados_2019.csv"
dados_tratados_2020 = "dados/dados_tratados_2020.csv"

# Lendo os arquivos CSV
df_2015 = pd.read_csv(dados_tratados_2015)
df_2016 = pd.read_csv(dados_tratados_2016)
df_2017 = pd.read_csv(dados_tratados_2017)
df_2018 = pd.read_csv(dados_tratados_2018)
df_2019 = pd.read_csv(dados_tratados_2019)
df_2020 = pd.read_csv(dados_tratados_2020)

# Empilhando todos os anos em um único DataFrame
df_total = pd.concat([df_2015, df_2016, df_2017, df_2018, df_2019, df_2020], ignore_index=True)

# ---------------------------------------------------------
# CORREÇÃO E NORMALIZAÇÃO DO PIB
# ---------------------------------------------------------
if df_total['PIB'].dtype == 'object':
    df_total['PIB'] = df_total['PIB'].str.replace(r'R\$\s*', '', regex=True)
    df_total['PIB'] = df_total['PIB'].str.replace('.', '', regex=False)
    df_total['PIB'] = df_total['PIB'].str.replace(',', '.', regex=False)
    df_total['PIB'] = df_total['PIB'].astype(float)

#Um erro de formatação causou com que o PIB ficasse em quadrilhões; aqui corrigimos para bilhões
df_total.loc[df_total['PIB'] > 1e12, 'PIB'] = df_total['PIB'] / 1e9

df_total['PIB_Bilhoes'] = (df_total['PIB'] * 1000) / 1e9
df_total['PIB_Bilhoes'] = df_total['PIB_Bilhoes'].round(2)

print(df_total.head())

# Resumo estatístico (Média, Desvio Padrão, Mínimo e Máximo)
print(df_total[['total_vitima', 'PIB_Bilhoes']].describe())

# Mediana (importante para comparar com a média)
print("Mediana de Vítimas:", df_total['total_vitima'].median())
print("Mediana do PIB:", df_total['PIB_Bilhoes'].median())

# Plotando gráfico de outliers
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 2))
sns.boxplot(x=df_total['PIB_Bilhoes'])
plt.title('Distribuição do PIB (Identificando Outliers)')
plt.show()

import plotly.express as px

#gráfico scatter
fig = px.scatter(
    df_total,
    x='PIB_Bilhoes',
    y='total_vitima',
    color='ano',
    hover_data=['municipio'],
    title='Relação entre PIB (em Bilhões) e Total de Vítimas',
    labels={'PIB_Bilhoes': 'PIB do Município', 'total_vitima': 'Total de Vítimas'},
    width=800,   # Define a largura
    height=500   # Define a altura
)

fig.show()

#Histograma para verificar a concentração dos casos de violência
fig_hist = px.histogram(
    df_total,
    x='total_vitima',
    nbins=30,
    title='Frequência da Quantidade de Vítimas (Concentração do Problema)',
    labels={'total_vitima': 'Total de Vítimas'},
    width=800,   # Define a largura
    height=500   # Define a altura
)
fig_hist.show()